<?php

/**
 * @file
 * Provides a CKEditor plugin and text filter for embedding and rendering entities.
 */

/**
 * A string that signifies not to render the alt text.
 */
define('ENTITY_EMBED_EMPTY_STRING', '""');

// HTML processing functions.
require_once dirname(__FILE__) . '/includes/entity_embed.html.inc';

// AJAX commands.
require_once dirname(__FILE__) . '/includes/entity_embed.commands.inc';

// Display functions.
require_once dirname(__FILE__) . '/includes/entity_embed.display.inc';

// Filter hooks and callbacks.
require_once dirname(__FILE__) . '/includes/entity_embed.filters.inc';

/**
 * Implements hook_permission().
 */
function entity_embed_permission() {
  return array(
    'administer embed buttons' => array(
      'title' => t('Administer entity embed buttons'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function entity_embed_menu() {
  $items['entity-embed/preview/%entity_embed_filter_format'] = array(
    'title' => 'Preview embedded entity',
    'page callback' => 'entity_embed_preview',
    'page arguments' => array(2),
    'access callback' => 'editor_dialog_access',
    'access arguments' => array(2, 'entity_embed'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );

  $items['entity-embed/dialog/%entity_embed_filter_format/%entity_embed_embed_button'] = array(
    'title' => 'Add/Edit embedded entity',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entity_embed_dialog_form', 2, 3),
    'access callback' => 'entity_embed_embed_button_format_access_check',
    'access arguments' => array(2, 3),
    'file' => 'entity_embed.admin.inc',
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function entity_embed_help($path, $arg) {
  switch ($path) {
    case 'admin/help#entity_embed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal represents content as different types of entities: nodes, files, users, taxonomy terms, etc. Entity Embed allows entities to be embedded in other entities, for example an image (file entity) may be embedded within a page (node entity). Users embed entities via WYSIWYG through one or more buttons. A button to embed content (nodes) is provided by default but additional buttons can be configured on the <a href="@entity_embed">Entity Embed administration page</a>.', array('@entity_embed' => url('admin/config/content/embed-button'))) . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Configure the jQuery Update module to use jQuery 1.7 or higher by visiting the <a href="@jquery_update">jQuery Update configuration page</a>.', array('@jquery_update' => url('admin/config/development/jquery_update'))) . '</li>';
      $output .= '<li>' . t('Enable the entity-embed filter <em>Display embedded entities</em> for the desired text formats from the <a href="@filter">Text Formats configuration page</a>.', array('@filter' => url('admin/config/content/formats'))) . '</li>';
      $output .= '<li>' . t('If the <em>Limit allowed HTML tags</em> filter is enabled, add <code>&lt;drupal-entity&gt;</code> to the <em>Allowed HTML tags</em>') . '</li>';
      $output .= '<li>' . t('Optionally enable the editor-align filter <em>Align images</em> to allow positioning of embedded entities.') . '</li>';
      $output .= '<li>' . t('To enable the WYSIWYG plugin, move the entity-embed <code>E</code> button into the Active toolbar for the desired text formats from the <a href="@formats">text formats configuration page</a>.', array('@formats' => url('admin/config/content/formats'))) . '</li>';
      $output .= '</ol>';
      return $output;

    case 'admin/config/content/embed-button':
      return '<p>' . t("Embed buttons define the buttons that can be added to CKEditor's toolbar. All buttons correspond to the selcted entity type, although a particular entity type can have more than one button. After you've created the desired buttons, go to <a href='@formats'>text formats configuration</a> page to add them to CKEditor's toolbar for the desired text formats.", array('@formats' => url('admin/config/content/formats'))) . '</p>';
  }
}

/**
 * Implements hook_library().
 */
function entity_embed_library() {
  $libraries['entity_embed'] = array(
    'title' => 'Entity Embed',
    'website' => 'http://www.drupal.org',
    'version' => VERSION,
    'js' => array(
      drupal_get_path('module', 'entity_embed') . '/js/embed.js' => array(
        'weight' => 2,
      ),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'drupal.ajax'),
    ),
  );

  return $libraries;
}

/**
 * Loads a text format object from the database.
 *
 * @param $format_id
 *   The format ID.
 *
 * @return
 *   A fully-populated text format object, if the requested format exists and
 *   is enabled. If the format does not exist, or exists in the database but
 *   has been marked as disabled, FALSE is returned.
 *
 * @see filter_format_exists()
 */
function entity_embed_filter_format_load($format_id) {
  $formats = filter_formats();

  return isset($formats[$format_id]) ? $formats[$format_id] : FALSE;
}

/**
 * Creates a new embed button object.
 *
 * @param $set_defaults
 *   If TRUE, which is the default, then default values will be retrieved
 *   from schema fields and set on the object.
 *
 * @return
 *   An embed button object populated with default values.
 */
function entity_embed_embed_button_new($set_defaults = TRUE) {
  ctools_include('export');

  return ctools_export_new_object('entity_embed', $set_defaults);
}

/**
 * Loads an embed button object from the database.
 *
 * @param $name
 *   The name of the button to load.
 *
 * @return
 *   The loaded button object or FALSE if the button is not found.
 */
function entity_embed_embed_button_load($name) {
  ctools_include('export');

  $result = ctools_export_load_object('entity_embed', 'names', array($name));

  return isset($result[$name]) ? $result[$name] : FALSE;
}

/**
 * Loads multiple embed button objects from the database.
 *
 * @param $names
 *   An array of button names to load.
 *
 * @return
 *   An array of loaded button objects.
 */
function entity_embed_embed_button_load_multiple(array $names) {
  ctools_include('export');

  $results = ctools_export_load_object('entity_embed', 'names', $names);

  // Ensure no empty results are returned.
  return array_filter($results);
}

/**
 * Load all embed button objects from the database.
 *
 * @param $reset
 *   If TRUE, the static cache of all objects will be flushed prior to
 *   loading all. This can be important on listing pages where items
 *   might have changed on the page load.
 *
 * @return
 *   An array of all loaded embed button objects, keyed by the unique IDs of the
 *   export key.
 */
function entity_embed_embed_button_load_all($reset = FALSE) {
  ctools_include('export');

  if ($reset) {
    ctools_export_load_object_reset('entity_embed');
  }

  return ctools_export_load_object('entity_embed', 'all');
}

/**
 * Saves an embed button object to the database.
 *
 * @param $embed_button
 *   The embed button to save.
 */
function entity_embed_embed_button_save($embed_button) {
  ctools_include('export');

  $new_button_icon_fid = $embed_button->button_icon_fid;

  // Find the original button settings to see if they have been changed.
  if ($original = entity_embed_embed_button_load($embed_button->name)) {
    $old_button_icon_fid = $original->button_icon_fid;

    // If the button icon has changed, remove file usage from the old icon.
    if (!empty($old_button_icon_fid) && $old_button_icon_fid != $new_button_icon_fid) {
      if ($file = file_load($old_button_icon_fid)) {
        // Mark the old icon file as temporary since it is no longer needed.
        if ($file->status !== 0) {
          $file->status = 0;
          file_save($file);
        }

        file_usage_delete($file, 'entity_embed', $embed_button->name, 1);
      }
    }
  }

  // Add file usage information to the button icon if it is new.
  if ($new_button_icon_fid) {
    if ($file = file_load($new_button_icon_fid)) {
      // Mark the file as permanent so it won't be cleaned up by the system.
      if ($file->status !== FILE_STATUS_PERMANENT) {
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
      }

      $usage = file_usage_list($file);

      // Icons can only be used once per button.
      if (empty($usage['entity_embed'][$embed_button->name][1])) {
        file_usage_add($file, 'entity_embed', $embed_button->name, 1);
      }
    }
  }

  if ($embed_button->export_type & EXPORT_IN_DATABASE) {
    // Existing record.
    $update = array('cid');
  }
  else {
    // New record.
    $update = array();
    $embed_button->export_type = EXPORT_IN_DATABASE;
  }

  // Reset the ctools object cache so that the changes are picked up.
  ctools_export_load_object_reset('entity_embed');

  return drupal_write_record('entity_embed', $embed_button, $update);
}

/**
 * Deletes an embed button object from the database.
 *
 * @param $embed_button
 *   The embed button to delete or the button cid.
 */
function entity_embed_embed_button_delete($embed_button) {
  ctools_include('export');

  $button_icon_fid = $embed_button->button_icon_fid;

  // Remove file usage from the associated button icon.
  if ($button_icon_fid) {
    if ($file = file_load($button_icon_fid)) {
      // Mark the file as temporary since it is no longer needed.
      if ($file->status !== 0) {
        $file->status = 0;
        file_save($file);
      }

      file_usage_delete($file, 'entity_embed', $embed_button->name, 1);
    }
  }

  $value = is_object($embed_button) ? $embed_button->cid : $embed_button;
  db_delete('entity_embed')
    ->condition('cid', $value)
    ->execute();
}

/**
 * Checks whether the embed button is enabled for the given text editor.
 *
 * @param $format
 *   A text format object.
 *
 * @return
 *   TRUE if entities can be previewed for the specified filter format, FALSE
 *   otherwise.
 *
 * @see entity_embed_menu()
 */
function entity_embed_embed_button_format_access_check($filter_format, $embed_button) {
  return editor_dialog_access($filter_format, 'entity_embed') && entity_embed_button_is_enabled($filter_format, $embed_button);
}

/**
 * Checks if the embed button is enabled in a text format.
 *
 * @param $filter_format
 *   The filter format to check.
 * @param $embed_button
 *   The embed button to check.
 *
 * @return boolean
 *   The access result.
 */
function entity_embed_button_is_enabled($filter_format, $embed_button) {
  editor_format_ensure_additional_properties($filter_format);

  if (!in_array($filter_format->editor, array('ckeditor', 'ckeditor5'), TRUE)) {
    return FALSE;
  }

  $has_button = FALSE;
  $settings = $filter_format->editor_settings;
  if ($filter_format->editor === 'ckeditor') {
    foreach ($settings['toolbar'] as $row) {
      foreach ($row as $group) {
        if (in_array($embed_button->name, $group['items'])) {
          $has_button = TRUE;
          break 2;
        }
      }
    }
  }
  elseif ($filter_format->editor === 'ckeditor5') {
    // The schema for CKEditor5 has changed, therefore we need to check for
    // the toolbar items differently.
    if ($settings['toolbar']['items'] && in_array($embed_button->name, $settings['toolbar']['items'])) {
      $has_button = TRUE;
    }
  }

  return $has_button;
}

/**
 * Implements hook_flush_caches().
 */
function entity_embed_flush_caches() {
  return array('cache_entity_embed');
}

/**
 * Returns an Ajax response to generate preview of an entity.
 *
 * Expects the the HTML element as GET parameter.
 *
 * @param $filter_format
 *   The filter format.
 *
 * @return
 *   The Ajax response.
 */
function entity_embed_preview($filter_format) {
  $query_parameters = drupal_get_query_parameters();
  $text = isset($query_parameters['text']) ? $query_parameters['text'] : $query_parameters['value'];

  if ($text == '') {
    drupal_exit();
  }

  // @todo: remove contextual links.
  $entity_output = check_markup($text, $filter_format->format);

  if (dialog_is_ajax()) {
    $commands = array();
    $commands[] = entity_embed_command_insert($entity_output);
    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    echo $entity_output;
    drupal_exit();
  }
}

/**
 * Helper function to create a URL to an embed button icon.
 *
 * @param int $fid
 *   A file ID.
 *
 * @return string
 *   A string containing a URL that may be used to access the file.
 */
function _entity_embed_button_image($fid) {
  $url = file_create_url(drupal_get_path('module', 'entity_embed') . '/js/plugins/drupalentity/entity.png');

  if ($fid) {
    if ($file = file_load($fid)) {
      $url = file_create_url($file->uri);
    }
  }

  return $url;
}

/**
 * Implements hook_entity_embed_field_formatters_alter().
 */
function entity_embed_entity_embed_field_formatters_alter(&$formatters, $entity_type, $entity) {
  foreach ($formatters as $formatter => $info) {
    // Files require special handling.
    if ($entity_type == 'file') {
      // Files behave differently depending on whether the File Entity module is
      // available.
      if (module_exists('file_entity')) {
        // With the File Entity module enabled, file entities require some
        // special handling. Unlike standard field formatters which specify a
        // list of compatible entity types and will work with any entity as long
        // as it is the correct type, file formatters may only support files
        // with specific MIME types.
        if (isset($entity) && isset($info['file formatter']['mime types']) && isset($entity->filemime)) {
          if (!file_entity_match_mimetypes($info['file formatter']['mime types'], $entity->filemime)) {
            // Skip the incompatible formatter.
            unset($formatters[$formatter]);
          }
        }
      }
      else {
        // The 'Rendered entity' formatter can not be used for files unless the
        // File Entity module is available.
        if ($formatter == 'entityreference_entity_view') {
          // Skip the incompatible formatter.
          unset($formatters[$formatter]);
        }
      }
    }

    // With the File Image Formatters module enabled, image field formatters
    // will appear twice.
    if ($info['module'] == 'file_image_formatters' && module_exists('file_image_formatters')) {
      // Skip the duplicate formatter.
      unset($formatters[$formatter]);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function entity_embed_form_filter_admin_format_form_alter(&$form, &$form_state, $form_id) {
  // Add an additional validate callback so we can ensure the order of filters
  // is correct.
  $form['#validate'][] = 'entity_embed_filter_format_edit_form_validate';
}

/**
 * Validate callback to ensure filter order and allowed_html are compatible.
 */
function entity_embed_filter_format_edit_form_validate($form, &$form_state) {
  // This validate handler is not applicable when using the 'Configure' button.
  if ($form_state['triggering_element']['#name'] === 'editor_configure') {
    return;
  }

  $allowed_html_path = $form_state['values']['filters']['filter_html']['settings']['allowed_html'];

  $button_group_path = $form_state['values']['editor']['settings']['toolbar']['button_groups'];

  $filter_html_settings_path = $form_state['values']['filters']['filter_html']['settings'];

  $filter_html_enabled = $form_state['values']['filters']['filter_html']['status'];

  $entity_embed_enabled = $form_state['values']['filters']['entity_embed']['status'];

  if ($entity_embed_enabled && $filter_html_enabled && $allowed_html_path) {
    if ($button_groups = $button_group_path) {
      $buttons = array();
      $button_groups = json_decode($button_groups, TRUE);
      if (!empty($button_groups[0])) {
        foreach ($button_groups[0] as $button_group) {
          foreach ($button_group['items'] as $item) {
            $buttons[] = $item;
          }
        }
      }

      /** @var object $filter_format */
      $filter_format = $form_state['build_info']['args'][0];

      $filter_html = (object) $filter_format->filters['filter_html'];
      $filter_html->settings = $filter_html_settings_path;
      $restrictions = editor_filter_html_get_html_restrictions($filter_html);
      $allowed = $restrictions['allowed'];

      $embeds = entity_embed_embed_button_load_multiple($buttons);

      /** @var object $embed */
      foreach ($embeds as $embed) {
        // Require `<drupal-entity>` HTML tag if filter_html is enabled.
        if (!isset($allowed['drupal-entity'])) {
          form_error($form['filters']['settings']['filter_html']['allowed_html'], t('The %embed button requires <code>&lt;drupal-entity&gt;</code> among the allowed HTML tags.', array(
            '%embed' => $embed->label,
          )));
          break;
        }
        else {
          $required_attributes = array(
            'data-entity-type',
            'data-entity-uuid',
            'data-entity-embed-display',
            'data-entity-embed-display-settings',
            'data-align',
            'data-caption',
            'data-embed-button',
            'alt',
            'title',
          );

          // If there are no attributes, the allowed item is set to FALSE,
          // otherwise, it is set to an array.
          if ($allowed['drupal-entity'] === FALSE) {
            $missing_attributes = $required_attributes;
          }
          else {
            // If any of the attributes on the drupal-entity tag use wildcards,
            // iterate through and replace them with matching required
            // attributes.
            $wildcards = preg_grep('/\*/', array_keys($allowed['drupal-entity']));
            if (!empty($wildcards)) {
              foreach ($wildcards as $wildcard) {
                $pattern = str_replace('*', '(.*)', $wildcard);
                $matches = preg_grep('/' . $pattern . '/', $required_attributes);
                foreach ($matches as $match) {
                  $allowed['drupal-entity'][$match] = 1;
                }
                unset($allowed['drupal-entity'][$wildcard]);
              }
            }
            $missing_attributes = array_diff($required_attributes, array_keys($allowed['drupal-entity']));
          }

          if ($missing_attributes) {
            form_error($form['filters']['settings']['filter_html']['allowed_html'], t('The <code>&lt;drupal-entity&gt;</code> tag in the allowed HTML tags is missing the following attributes: <code>%list</code>.', array(
              '%list' => implode(', ', $missing_attributes),
            )));
            break;
          }
        }
      }
    }
  }

  $filters = $form_state['values']['filters'];

  $get_filter_label = function ($filter_plugin_id) use ($form) {
    return (string) $form['filters']['order'][$filter_plugin_id]['filter']['#markup'];
  };

  // The "entity_embed" filter must run after "editor_align", "editor_caption",
  // and "filter_html_image_secure".
  if ($entity_embed_enabled) {
    $precedents = array(
      'editor_align',
      'editor_caption',
    );

    $error_filters = array();
    foreach ($precedents as $filter_name) {

      // A filter that should run before entity embed filter.
      $precedent = $filters[$filter_name];

      if (empty($precedent['status']) || !isset($precedent['weight'])) {
        continue;
      }

      if ($precedent['weight'] >= $filters['entity_embed']['weight']) {
        $error_filters[$filter_name] = $get_filter_label($filter_name);
      }
    }

    if (!empty($error_filters)) {
      $singular = 'The %entity-embed-filter-label filter needs to be placed after the %filter filter.';
      $plural = 'The %entity-embed-filter-label filter needs to be placed after the following filters: %filters.';
      $error_message = format_plural(count($error_filters), $singular, $plural,  array(
        '%entity-embed-filter-label' => $get_filter_label('entity_embed'),
        '%filter' => reset($error_filters),
        '%filters' => implode(', ', $error_filters),
      ));

      form_set_error('filters][entity_embed][status', $error_message);
    }
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function entity_embed_field_widget_form_alter(&$element, &$form_state, $context) {
  // Add a `data-entity_embed-host-entity-langcode` attribute so that
  // entity_embed's JavaScript can pass the host entity's language to
  // EntityEmbedDialog, allowing it to present entities in the same language.
  if (isset($element['#type']) && $element['#type'] === 'text_format') {
    $element['#attributes']['data-entity_embed-host-entity-langcode'] = $context['langcode'];
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function entity_embed_ctools_plugin_api($module, $api) {
  if ($module == 'entity_embed' && $api == 'default_entity_embed_configurations') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function entity_embed_ctools_plugin_directory($module, $plugin) {
  if ($plugin =='export_ui') {
    return 'plugins/export_ui';
  }
}
